-- ============================================================
-- TASK-087: 현재 activity_logs 액션의 한글 라벨 보완
--
-- 목적
--   activity_logs에 실제로 존재하는 액션 중, code_items에 한글 라벨이
--   없거나 영문 라벨만 있는 액션만 한글 라벨로 보완한다.
--
-- 동작
--   - 현재 activity_logs.action에 존재하는 코드만 대상으로 한다.
--   - 이미 한글 라벨이 있는 코드와 메타데이터/정렬 순서는 유지한다.
--   - 코드북에 없는 액션은 레거시 정렬 순번(990000)으로 새로 추가한다.
-- ============================================================

BEGIN;

WITH translations (code_key, code_value) AS (
  VALUES
    ('PAGE_VIEW', '페이지 조회'),
    ('JS_ERROR', 'JS 오류'),
    ('PROMISE_REJECTION', '비동기 오류'),
    ('CONNECTION_FAIL', '연결 실패'),
    ('APP_VERSION_STALE_SESSION', '구버전 세션 감지'),
    ('USER_CREATE', '사용자 등록'),
    ('USER_CREATE_FAIL', '사용자 등록 실패'),
    ('USER_CREATE_DENIED', '사용자 등록 거부'),
    ('USER_CREATE_ERROR', '사용자 등록 오류'),
    ('USER_UPDATE', '사용자 수정'),
    ('USER_UPDATE_FAIL', '사용자 수정 실패'),
    ('USER_UPDATE_DENIED', '사용자 수정 거부'),
    ('USER_UPDATE_ERROR', '사용자 수정 오류'),
    ('SLACK_NOTIFY_FAIL', 'Slack 알림 전송 실패'),
    ('USER_DELETE', '사용자 삭제'),
    ('USER_DELETE_FAIL', '사용자 삭제 실패'),
    ('USER_DELETE_DENIED', '사용자 삭제 거부'),
    ('USER_DELETE_ERROR', '사용자 삭제 오류'),
    ('USER_PW_RESET', '비밀번호 초기화'),
    ('USER_PW_RESET_FAIL', '비밀번호 초기화 실패'),
    ('USER_ID_CHECK_FAIL', '아이디 중복 확인 실패'),
    ('USER_ID_CHECK_DUPLICATE', '아이디 중복'),
    ('PASSWORD_RESET', '비밀번호 초기화'),
    ('PASSWORD_RESET_FAIL', '비밀번호 초기화 실패'),
    ('PASSWORD_RESET_DENIED', '비밀번호 초기화 거부'),
    ('PASSWORD_RESET_ERROR', '비밀번호 초기화 오류'),
    ('REGISTER_REQUEST', '가입 신청'),
    ('REGISTER_REQUEST_FAIL', '가입 신청 실패'),
    ('REGISTER_APPROVE', '가입 승인'),
    ('REGISTER_APPROVE_FAIL', '가입 승인 실패'),
    ('REGISTER_REJECT', '가입 거부'),
    ('BULK_REGISTER', '학생 일괄 등록'),
    ('LOGIN_SUCCESS', '로그인 성공'),
    ('LOGIN_FAIL', '로그인 실패'),
    ('LOGIN_ERROR', '로그인 오류'),
    ('LOGIN_PENDING_APPROVAL', '가입 승인 대기'),
    ('AUTH_SESSION_MISSING', '인증 세션 없음'),
    ('AUTH_PROFILE_LOAD_FAIL', '인증 프로필 조회 실패'),
    ('AUTH_REDIRECT', '인증/권한 리디렉트'),
    ('AUTH_PAGE_ACCESS_CHECK_FAIL', '페이지 접근 권한 확인 실패'),
    ('QR_LOCATION_PERMISSION_BLOCKED', 'QR 위치 권한 차단'),
    ('LOGOUT', '로그아웃'),
    ('PASSWORD_CHANGE', '비밀번호 변경'),
    ('PASSWORD_CHANGE_FAIL', '비밀번호 변경 실패'),
    ('PASSWORD_CHANGE_ERROR', '비밀번호 변경 오류'),
    ('DEPT_CREATE', '부서 등록'),
    ('DEPT_CREATE_FAIL', '부서 등록 실패'),
    ('DEPT_CREATE_ERROR', '부서 등록 오류'),
    ('DEPT_UPDATE', '부서 수정'),
    ('DEPT_UPDATE_FAIL', '부서 수정 실패'),
    ('DEPT_UPDATE_ERROR', '부서 수정 오류'),
    ('DEPT_DELETE', '부서 삭제'),
    ('DEPT_DELETE_FAIL', '부서 삭제 실패'),
    ('DEPT_DELETE_ERROR', '부서 삭제 오류'),
    ('DEPT_DEACTIVATE', '부서 비활성화'),
    ('DEPT_TRANSFER_IMMEDIATE', '부서 즉시 이동'),
    ('DEPT_TRANSFER_IMMEDIATE_FAIL', '부서 즉시 이동 실패'),
    ('DEPT_TRANSFER_REQUEST', '부서 이동 요청'),
    ('DEPT_TRANSFER_REQUEST_FAIL', '부서 이동 요청 실패'),
    ('DEPT_TRANSFER_APPROVE', '부서 이동 승인'),
    ('DEPT_TRANSFER_REJECT', '부서 이동 거부'),
    ('MANAGER_UPDATE', '관리자 수정'),
    ('MANAGER_UPDATE_FAIL', '관리자 수정 실패'),
    ('MANAGER_PROMOTE', '관리자 승격'),
    ('MANAGER_PROMOTE_FAIL', '관리자 승격 실패'),
    ('TALENT_GIVE', '달란트 지급'),
    ('TALENT_GIVE_FAIL', '달란트 지급 실패'),
    ('TALENT_GIVE_DENIED', '달란트 지급 거부'),
    ('TALENT_GIVE_ERROR', '달란트 지급 오류'),
    ('TALENT_GIVE_ITEM', '달란트 항목 지급'),
    ('TALENT_GIVE_ITEM_FAIL', '달란트 항목 지급 실패'),
    ('TALENT_GIVE_ITEM_DENIED', '달란트 항목 지급 거부'),
    ('TALENT_GIVE_ITEM_ERROR', '달란트 항목 지급 오류'),
    ('TALENT_GIVE_ITEMS', '달란트 일괄 지급'),
    ('TALENT_EXCEPTION_REQUEST', '예외 지급 요청'),
    ('TALENT_EXCEPTION_REQUEST_FAIL', '예외 지급 요청 실패'),
    ('TALENT_EXCEPTION_REQUEST_ERROR', '예외 지급 요청 오류'),
    ('TALENT_EXCEPTION_APPROVE', '예외 지급 승인'),
    ('TALENT_EXCEPTION_APPROVE_FAIL', '예외 지급 승인 실패'),
    ('TALENT_EXCEPTION_REJECT', '예외 지급 거부'),
    ('TALENT_EXCEPTION_REQUEST_UPDATE_FAIL', '예외 지급 요청 수정 실패'),
    ('TALENT_EXCEPTION_REQUEST_UPDATE_ERROR', '예외 지급 요청 수정 오류'),
    ('TALENT_MANUAL_GIVE', '달란트 수동 지급'),
    ('TALENT_MANUAL_GIVE_FAIL', '달란트 수동 지급 실패'),
    ('TALENT_MANUAL_GIVE_ERROR', '달란트 수동 지급 오류'),
    ('TALENT_USE', '달란트 사용'),
    ('TALENT_USE_FAIL', '달란트 사용 실패'),
    ('TALENT_USE_DENIED', '달란트 사용 거부'),
    ('TALENT_USE_ERROR', '달란트 사용 오류'),
    ('TALENT_RETURN', '달란트 반환'),
    ('TALENT_RETURN_FAIL', '달란트 반환 실패'),
    ('TALENT_RETURN_DENIED', '달란트 반환 거부'),
    ('TALENT_RETURN_ERROR', '달란트 반환 오류'),
    ('ATTENDANCE_GIVE', '출석 달란트 지급'),
    ('ATTENDANCE_CANCEL', '출석 달란트 취소'),
    ('TALENT_ITEM_CANCEL', '달란트 항목 취소'),
    ('TALENT_ITEM_CREATE', '달란트 항목 등록'),
    ('TALENT_ITEM_CREATE_FAIL', '달란트 항목 등록 실패'),
    ('TALENT_ITEM_UPDATE', '달란트 항목 수정'),
    ('TALENT_ITEM_UPDATE_FAIL', '달란트 항목 수정 실패'),
    ('TALENT_ITEM_TOGGLE', '달란트 항목 활성 토글'),
    ('TALENT_ITEM_QUICKBTN', '달란트 퀵버튼 설정'),
    ('qr_create', 'QR 코드 생성'),
    ('QR_CREATE_FAIL', 'QR 코드 생성 실패'),
    ('QR_CREATE_NO_RESULT', 'QR 코드 생성 결과 없음'),
    ('QR_CREATE_ERROR', 'QR 코드 생성 오류'),
    ('qr_edit', 'QR 코드 수정'),
    ('qr_toggle', 'QR 코드 토글'),
    ('qr_scan', 'QR 달란트 수령'),
    ('PRODUCT_CREATE', '상품 등록'),
    ('PRODUCT_BULK_CREATE', '상품 일괄 등록'),
    ('PRODUCT_CREATE_FAIL', '상품 등록 실패'),
    ('PRODUCT_CREATE_ERROR', '상품 등록 오류'),
    ('PRODUCT_CATEGORY_CREATE', '상품 카테고리 등록'),
    ('PRODUCT_CATEGORY_CREATE_FAIL', '상품 카테고리 등록 실패'),
    ('PRODUCT_CATEGORY_CREATE_ERROR', '상품 카테고리 등록 오류'),
    ('PRODUCT_CATEGORY_UPDATE', '상품 카테고리 수정'),
    ('PRODUCT_CATEGORY_UPDATE_FAIL', '상품 카테고리 수정 실패'),
    ('PRODUCT_CATEGORY_UPDATE_ERROR', '상품 카테고리 수정 오류'),
    ('PRODUCT_CATEGORY_DELETE', '상품 카테고리 삭제'),
    ('PRODUCT_CATEGORY_DELETE_FAIL', '상품 카테고리 삭제 실패'),
    ('PRODUCT_CATEGORY_DELETE_ERROR', '상품 카테고리 삭제 오류'),
    ('PRODUCT_UPDATE', '상품 수정'),
    ('PRODUCT_UPDATE_FAIL', '상품 수정 실패'),
    ('PRODUCT_UPDATE_ERROR', '상품 수정 오류'),
    ('PRODUCT_IMAGE_UPDATE', '상품 이미지 연결'),
    ('PRODUCT_IMAGE_UPDATE_FAIL', '상품 이미지 연결 실패'),
    ('PRODUCT_IMAGE_UPDATE_ERROR', '상품 이미지 연결 오류'),
    ('PRODUCT_DELETE', '상품 삭제'),
    ('PRODUCT_DELETE_FAIL', '상품 삭제 실패'),
    ('PRODUCT_DELETE_ERROR', '상품 삭제 오류'),
    ('PRODUCT_DEACTIVATE', '상품 비활성화'),
    ('PRODUCT_DEACTIVATE_FAIL', '상품 비활성화 실패'),
    ('PRODUCT_DEACTIVATE_ERROR', '상품 비활성화 오류'),
    ('PRODUCT_SOFT_DELETE', '상품 비활성화'),
    ('PRODUCT_SUGGESTION_CREATE', '상품 추천 등록'),
    ('PRODUCT_SUGGESTION_CREATE_FAIL', '상품 추천 등록 실패'),
    ('PRODUCT_SUGGESTION_ADOPT', '추천 상품 채택'),
    ('PRODUCT_SUGGESTION_REJECT', '추천 상품 불채택'),
    ('PRODUCT_SUGGESTION_CLOSE', '추천 상품 투표 종료'),
    ('PRODUCT_SUGGESTION_ADOPTION_TALENT', '상품 추천 채택 달란트 지급'),
    ('IMAGE_UPLOAD', '이미지 업로드'),
    ('IMAGE_COMPRESS_FAIL', '이미지 압축 실패'),
    ('IMAGE_UPLOAD_FAIL', '이미지 업로드 실패'),
    ('IMAGE_UPLOAD_ERROR', '이미지 업로드 오류'),
    ('IMAGE_DELETE_FAIL', '이미지 삭제 실패'),
    ('ORDER_REQUEST_SUCCESS', '상품 구매 신청'),
    ('ORDER_REQUEST_FAIL', '상품 구매 신청 실패'),
    ('ORDER_REQUEST_DENIED', '상품 구매 신청 거부'),
    ('ORDER_REQUEST_ERROR', '상품 구매 신청 오류'),
    ('ORDER_INSUFFICIENT_BALANCE', '달란트 부족으로 구매 불가'),
    ('PROXY_ORDER_SUCCESS', '대리 구매 신청'),
    ('PROXY_ORDER_FAIL', '대리 구매 신청 실패'),
    ('PROXY_ORDER_DENIED', '대리 구매 신청 거부'),
    ('PROXY_ORDER_ERROR', '대리 구매 신청 오류'),
    ('PROXY_USER_LOAD_FAIL', '대리 구매 사용자 조회 실패'),
    ('PROXY_USER_LOAD_ERROR', '대리 구매 사용자 조회 오류'),
    ('order_cancel', '주문 취소'),
    ('ORDER_STATUS_CHANGE', '주문 상태 변경'),
    ('ORDER_STATUS_CHANGE_FAIL', '주문 상태 변경 실패'),
    ('ORDER_STATUS_CHANGE_ERROR', '주문 상태 변경 오류'),
    ('ORDER_REVERT', '주문 상태 되돌리기'),
    ('ORDER_REVERT_FAIL', '주문 상태 되돌리기 실패'),
    ('ORDER_REVERT_ERROR', '주문 상태 되돌리기 오류'),
    ('ORDER_PURCHASE_CONFIRM', '구매 확정'),
    ('ORDER_PURCHASE_CONFIRM_FAIL', '구매 확정 실패'),
    ('ORDER_PURCHASE_CONFIRM_DENIED', '구매 확정 거부'),
    ('ORDER_PURCHASE_CONFIRM_ERROR', '구매 확정 오류'),
    ('ORDER_BULK_PREPARE', '일괄 상품 준비'),
    ('ORDER_BULK_PREPARE_ITEM_FAIL', '일괄 상품 준비 항목 실패'),
    ('ORDER_BULK_PURCHASE', '일괄 구매 확정'),
    ('ORDER_BULK_PURCHASE_ITEM_FAIL', '일괄 구매 확정 항목 실패'),
    ('ORDER_BULK_PURCHASE_DENIED', '일괄 구매 확정 거부'),
    ('ORDER_BULK_DELIVER', '일괄 상품 지급'),
    ('ORDER_BULK_DELIVER_ITEM_FAIL', '일괄 상품 지급 항목 실패'),
    ('PURCHASE_LOAD_FAIL', '구매 데이터 조회 실패'),
    ('PURCHASE_SCOPE_USERS_FAIL', '구매 범위 사용자 조회 실패'),
    ('SHOP_PROFILE_FALLBACK', '상점 프로필 폴백'),
    ('MY_ORDERS_FETCH', '내 주문 조회 실패'),
    ('MY_TALENT_PENDING_QUERY', '대기 달란트 조회 오류'),
    ('MY_TALENT_ORDERS_QUERY', '주문 조회 오류'),
    ('ORDER_CANCEL', '주문 취소'),
    ('ORDER_CANCEL_REFUND_FAIL', '주문 취소 환불 실패'),
    ('QNA_CREATE', '질문 등록'),
    ('QNA_ANSWER', '답변 등록'),
    ('QNA_COMMENT', '댓글 등록'),
    ('QNA_DELETE', 'Q&A 삭제'),
    ('QNA_FAQ_SET', 'FAQ 설정'),
    ('ANNOUNCEMENT_VIEW', '공지 조회'),
    ('ANNOUNCEMENT_READ_STATUS_VIEW', '공지 열람 현황 조회'),
    ('ANNOUNCEMENT_CREATE', '공지 등록'),
    ('ANNOUNCEMENT_CREATE_FAIL', '공지 등록 실패'),
    ('ANNOUNCEMENT_UPDATE', '공지 수정'),
    ('ANNOUNCEMENT_UPDATE_FAIL', '공지 수정 실패'),
    ('ANNOUNCEMENT_TOGGLE', '공지 활성 토글'),
    ('ANNOUNCEMENT_TOGGLE_FAIL', '공지 활성 토글 실패'),
    ('ANNOUNCEMENT_DELETE', '공지 삭제'),
    ('ANNOUNCEMENT_DELETE_FAIL', '공지 삭제 실패'),
    ('ANNOUNCEMENT_LOAD_FAIL', '공지 조회 실패'),
    ('ANNOUNCEMENT_DISMISS', '공지 다시 열지 않음'),
    ('ANNOUNCEMENT_DISMISS_FAIL', '공지 다시 열지 않음 실패'),
    ('ANNOUNCEMENT_SAVE_ERROR', '공지 저장 오류'),
    ('LOG_ACKNOWLEDGED', '로그 확인'),
    ('LOG_BULK_ACK', '로그 일괄 확인'),
    ('LOG_RANGE_DELETE', '로그 범위 삭제'),
    ('LOG_RANGE_DELETE_FAIL', '로그 범위 삭제 실패'),
    ('LOG_RANGE_DELETE_ERROR', '로그 범위 삭제 오류'),
    ('LOG_SELECT_DELETE', '로그 선택 삭제'),
    ('LOG_SELECT_DELETE_FAIL', '로그 선택 삭제 실패'),
    ('LOG_SELECT_DELETE_ERROR', '로그 선택 삭제 오류'),
    ('LOG_RESTORE', '로그 복원'),
    ('LOG_RESTORE_FAIL', '로그 복원 실패'),
    ('LOG_RETENTION_CLEANUP', '180일 초과 로그 실제 삭제'),
    ('LOG_RETENTION_CLEANUP_FAIL', '180일 초과 로그 실제 삭제 실패'),
    ('ROLE_ACCESS_UPDATE', '페이지 접근 권한 변경'),
    ('ROLE_ACCESS_UPDATE_FAIL', '페이지 접근 권한 변경 실패'),
    ('ROLE_FEATURE_UPDATE', '페이지 기능 권한 변경'),
    ('ROLE_FEATURE_UPDATE_FAIL', '페이지 기능 권한 변경 실패'),
    ('PAGE_PERM_UPDATE', '페이지 권한 설정 변경'),
    ('REPORT_VIEW', '보고서 조회'),
    ('REPORT_SAVE', '보고서 저장'),
    ('REPORT_SAVE_FAIL', '보고서 저장 실패'),
    ('REPORT_SAVE_ERROR', '보고서 저장 오류'),
    ('REPORT_DELETE', '보고서 삭제'),
    ('REPORT_DELETE_FAIL', '보고서 삭제 실패'),
    ('REPORT_DELETE_ERROR', '보고서 삭제 오류'),
    ('REPORT_SEED', '보고서 시드 등록'),
    ('REPORT_SEED_FAIL', '보고서 시드 등록 실패'),
    ('REPORT_SEED_ERROR', '보고서 시드 등록 오류'),
    ('SERVICE_USAGE_COLLECT_FAIL', '서비스 사용량 수집 실패'),
    ('SERVICE_USAGE_RETENTION_CLEANUP', '서비스 통계 180일 초과 정리'),
    ('SERVICE_USAGE_RETENTION_CLEANUP_FAIL', '서비스 통계 180일 초과 정리 실패')
),
current_log_actions AS (
  SELECT DISTINCT btrim(action) AS code_key
  FROM public.activity_logs
  WHERE action IS NOT NULL
    AND btrim(action) <> ''
),
target_actions AS (
  SELECT t.code_key, t.code_value
  FROM translations t
  INNER JOIN current_log_actions l USING (code_key)
)
INSERT INTO public.code_items (
  group_key,
  code_key,
  code_value,
  sort_order,
  is_active,
  meta
)
SELECT
  'activity_logs.action',
  code_key,
  code_value,
  990000,
  true,
  '{"source":"TASK-087"}'::jsonb
FROM target_actions
ON CONFLICT (group_key, code_key) DO UPDATE
SET code_value = EXCLUDED.code_value,
    is_active = true,
    updated_at = now()
WHERE COALESCE(btrim(public.code_items.code_value), '') = ''
   OR public.code_items.code_value = public.code_items.code_key
   OR public.code_items.code_value !~ '[가-힣]'
RETURNING code_key, code_value;

COMMIT;
